Repository cablelabs/transparent-security, pull requests merged in 2020-11, with the labels that each got.

#297 Fix packet loss with data_inspection tests
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
Labels: bug

#299 Controller and P4 refactoring for TNA & the Lab Trial
  automation/p4/tofino/scenarios.tf
  automation/p4/tofino/setup.tf
  automation/p4/tofino/variables.tf
  bin/sdn_controller.py
  p4/aggregate/aggregate_tna.p4
  p4/core/core_tna.p4
  playbooks/general/setup_source.yml
  playbooks/general/templates/sdn_controller.sh.j2
  playbooks/mininet/setup-full.yml
  playbooks/mininet/setup-lab_trial.yml
  playbooks/mininet/setup-single_switch.yml
  playbooks/scenarios/aggregate/data-inspection.yml
  playbooks/scenarios/core/data-forward.yml
  playbooks/scenarios/core/data-inspection.yml
  playbooks/scenarios/gateway/data-inspection.yml
  playbooks/scenarios/general/data_drop_basic.yml
  playbooks/scenarios/general/data_forward_basic.yml
  playbooks/scenarios/lab_trial/data-drop.yml
  playbooks/scenarios/lab_trial/data-forward.yml
  playbooks/scenarios/lab_trial/data-inspection.yml
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
  playbooks/scenarios/single_switch/data_inspection_basic.yml
  playbooks/scenarios/test_cases/send_receive.yml
  playbooks/tofino/setup_nodes-full.yml
  playbooks/tofino/setup_nodes-lab_trial.yml
  playbooks/tofino/setup_nodes-single_switch.yml
  playbooks/tofino/templates/node_setup_test_inventory.yml.j2
  playbooks/tofino/templates/topology_template-full.yaml.j2
  playbooks/tofino/templates/topology_template-lab_trial.yaml.j2
  playbooks/tofino/templates/topology_template-single_switch.yaml.j2
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/bfruntime_lib/bfrt_switch.py
  trans_sec/bfruntime_lib/core_switch.py
  trans_sec/controller/abstract_controller.py
  trans_sec/controller/aggregate_controller.py
  trans_sec/controller/core_controller.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/controller/http_server_flask.py
  trans_sec/switch.py
Labels: enhancement

#302 Agg return path
  p4/aggregate/aggregate_tna.p4
  p4/include/tps_consts.p4
  p4/include/tps_headers.p4
  playbooks/scenarios/test_cases/send_receive.yml
  playbooks/tofino/templates/topology_template-lab_trial.yaml.j2
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/bfruntime_lib/bfrt_switch.py
  trans_sec/bfruntime_lib/core_switch.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/device_software/receive_packets.py
  trans_sec/device_software/send_packets.py
  trans_sec/p4runtime_lib/p4rt_switch.py
  trans_sec/switch.py
Labels: enhancement

#321 Tcp testing
  p4/aggregate/aggregate_tna.p4
  playbooks/general/setup_source.yml
  playbooks/scenarios/general/arping.yml
  playbooks/scenarios/lab_trial/all-data-drop.yml
  playbooks/scenarios/lab_trial/all-data-forward.yml
  playbooks/scenarios/lab_trial/all-data-inspection.yml
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
  playbooks/scenarios/lab_trial/all.yml
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
  playbooks/scenarios/lab_trial/discover-paths.yml
  playbooks/scenarios/lab_trial/iperf.yml
  playbooks/scenarios/lab_trial/restart.yml
  playbooks/scenarios/lab_trial/restart_services.yml
  playbooks/scenarios/test_cases/run_iperf.yml
Labels: enhancement, lab trial

#329 Implemented TNA Register in core_tna.p4 for sampling of Telemetry Reports
  p4/core/core_tna.p4
Labels: enhancement

#330 Created web service to set Telemetry Report sample rate
  playbooks/scenarios/aggregate/data-drop.yml
  playbooks/scenarios/aggregate/data-forward.yml
  playbooks/scenarios/aggregate/data-inspection.yml
  playbooks/scenarios/core/data-forward.yml
  playbooks/scenarios/core/data-inspection.yml
  playbooks/scenarios/lab_trial/all-data-inspection.yml
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
  playbooks/scenarios/lab_trial/data-drop.yml
  playbooks/scenarios/lab_trial/data-forward.yml
  playbooks/scenarios/lab_trial/data-inspection.yml
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
  playbooks/scenarios/test_cases/send_receive.yml
  playbooks/tofino/templates/topology_template-lab_trial.yaml.j2
  playbooks/tofino/templates/topology_template-single_switch.yaml.j2
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/bfruntime_lib/core_switch.py
  trans_sec/controller/core_controller.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/controller/http_server_flask.py
Labels: enhancement, lab trial

#332 Added ansible script to load index patterns
  automation/p4/tofino/variables.tf
  playbooks/ae/setup_ae_elk.yml
  playbooks/ae/templates/index_pattern_request_body.json
  playbooks/ae/templates/opendistro_elasticsearch.sh
  playbooks/tofino/setup_nodes-lab_trial.yml
Labels: enhancement

#334 Refactor data-inspection actions from ingress to egress
  p4/aggregate/aggregate_tna.p4
  p4/include/tna_mirror.p4
  trans_sec/bfruntime_lib/aggregate_switch.py
Labels: enhancement

#335 Configure switch default port
  p4/aggregate/aggregate_tna.p4
  p4/core/core_tna.p4
  p4/include/tps_consts.p4
  playbooks/scenarios/aggregate/data-drop.yml
  playbooks/scenarios/aggregate/data-forward.yml
  playbooks/scenarios/aggregate/data-inspection.yml
  playbooks/scenarios/core/data-forward.yml
  playbooks/scenarios/core/data-inspection.yml
  playbooks/scenarios/lab_trial/data-drop.yml
  playbooks/scenarios/lab_trial/data-inspection.yml
  playbooks/tofino/templates/topology_template-lab_trial.yaml.j2
  playbooks/tofino/templates/topology_template-single_switch.yaml.j2
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/bfruntime_lib/bfrt_switch.py
  trans_sec/bfruntime_lib/core_switch.py
Labels: bug, enhancement, lab trial
