Repository cablelabs/transparent-security, pull requests merged in 2020-01, with the labels that each got.

#54 Mininet simulation on localhost/VM
  automation/env-build/aws-inst.tf
  docs/BUILD.md
  docs/example-local-inventory.ini
  playbooks/env-build/mininet/env_build.yml
  playbooks/env-build/tofino/env_build.yml
Labels: documentation

#52 Fix broken pytests
  playbooks/general/setup_source.yml
  playbooks/mininet/setup_host.yml
  playbooks/tofino/setup_orchestrator.yml
  tests/trans_sec/controller/aggregate_controller_tests.py
  tests/trans_sec/controller/core_controller_tests.py
  tests/trans_sec/controller/gateway_controller_tests.py
Labels: bug

#62 Renamed the INT data structure
  p4/aggregate/aggregate.p4
  p4/core/core.p4
  p4/gateway/gateway.p4
  p4/include/tps_egress.p4
  p4/include/tps_headers.p4
  p4/include/tps_ingress.p4
  p4/include/tps_parser.p4
  tests/trans_sec/analytics/oinc_tests.py
  trans_sec/analytics/oinc.py
  trans_sec/controller/abstract_controller.py
  trans_sec/packet/inspect_layer.py
Labels: enhancement

#63 Changed workflow for mininet integration local inventory setup
  automation/p4/mininet/setup.tf
  automation/p4/mininet/variables.tf
  docs/BUILD.md
  playbooks/mininet/generate_inventory.yml
  playbooks/mininet/setup_mininet.yml
  playbooks/mininet/templates/local_inventory.ini.j2
Labels: enhancement

#67 Fix optional device daemons feature for mininet
  automation/p4/mininet/setup.tf
  playbooks/general/templates/mininet_service.sh.j2
Labels: bug
