Repository cablelabs/transparent-security, pull requests merged in 2020-12, with the labels that each got.

#339 Issue 323
  playbooks/ae/delete_ae_history.yml
  playbooks/ae/setup_ae_elk.yml
  playbooks/ae/setup_ae_tcp_pipeline.yml
  playbooks/ae/setup_ae_udp_pipeline.yml
  playbooks/ae/templates/sdn_attack_webhook.json
  playbooks/ae/templates/tcp/tcp_data_mapping.json
  playbooks/ae/templates/tcp/tcp_data_parsing.json
  playbooks/ae/templates/tcp/tcp_monitor_def.json
  playbooks/ae/templates/udp/udp_data_mapping.json
  playbooks/ae/templates/udp/udp_data_parsing.json
  playbooks/ae/templates/udp/udp_monitor_def.json
  playbooks/tofino/setup_nodes-lab_trial.yml
Labels: enhancement

#340 Swagger ws doc
  requirements.txt
  trans_sec/controller/http_server_flask.py
Labels: enhancement

#342 Split the startup routine of snaps-hcp to avoid the 3 min sleep
  playbooks/ae/conf_ae_elk.yml
  playbooks/ae/setup_ae_tcp_pipeline.yml
  playbooks/ae/setup_ae_udp_pipeline.yml
  playbooks/ae/start_ae_elk.yml
  playbooks/scenarios/lab_trial/restart_services.yml
  playbooks/tofino/setup_nodes-lab_trial.yml
Labels: enhancement

#344 Refactor AE Build Playbook
  automation/p4/tofino/variables.tf
  playbooks/ae/setup_ae_centos.yml
Labels: enhancement

#346 Issue 345
  playbooks/ae/templates/sdn_attack_webhook.json
  playbooks/ae/templates/tcp/tcp_data_mapping.json
  playbooks/ae/templates/tcp/tcp_data_parsing.json
  playbooks/ae/templates/tcp/tcp_monitor_def.json
  playbooks/ae/templates/udp/udp_data_mapping.json
  playbooks/ae/templates/udp/udp_data_parsing.json
  playbooks/ae/templates/udp/udp_monitor_def.json
Labels: bug

#347 Configure drop report frequency and fix AE endpoint
  bin/sdn_controller.py
  playbooks/general/templates/sdn_controller.sh.j2
  playbooks/scenarios/lab_trial/drop-rpt.yml
  playbooks/scenarios/lab_trial/drop_report.yml
  trans_sec/controller/core_controller.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/device_software/receive_packets.py
Labels: bug, enhancement

#350 Adds switch port configuration to SDN
  automation/p4/tofino/setup.tf
  automation/p4/tofino/variables.tf
  bin/sdn_controller.py
  conf/cl_hw_lab_trial/tofino-sim-topology-single-switch.yaml
  conf/cl_hw_lab_trial/tofino-sim-topology.yaml
  conf/cl_hw_lab_trial/transparent-security-single-switch.yaml
  conf/cl_hw_lab_trial/transparent-security.yaml
  playbooks/general/setup_source.yml
  playbooks/general/templates/sdn_controller.sh.j2
  playbooks/scenarios/lab_trial/configure_switches-lab_trial.yml
  playbooks/scenarios/lab_trial/discover-paths.yml
  playbooks/scenarios/lab_trial/iperf.yml
  playbooks/tofino/conf_switch_ports.yml
  playbooks/tofino/setup_nodes-lab_trial.yml
  playbooks/tofino/setup_nodes-single_switch.yml
  playbooks/tofino/setup_tofino_switch.yml
  playbooks/tofino/setup_virt_eth.yml
  playbooks/tofino/templates/node_setup_test_inventory.yml.j2
  playbooks/tofino/templates/switchd_service.sh.j2
  playbooks/tofino/templates/topology_template-lab_trial.yaml.j2
  playbooks/tofino/templates/topology_template-single_switch.yaml.j2
  playbooks/tofino/tunnel/setup_gre_tunnels.yml
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/bfruntime_lib/bfrt_switch.py
  trans_sec/bfruntime_lib/core_switch.py
  trans_sec/controller/abstract_controller.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/switch.py
Labels: enhancement, lab trial

#348 Added data inspection test that ingress INT into aggregate_tna.p4
  playbooks/scenarios/aggregate/data-inspection.yml
Labels: enhancement

#352 Validating drop report contents
  playbooks/scenarios/lab_trial/all-drop-rpt.yml
  playbooks/scenarios/lab_trial/all.yml
  playbooks/scenarios/lab_trial/drop-rpt.yml
  playbooks/scenarios/lab_trial/drop_report.yml
  playbooks/scenarios/lab_trial/drop_report_simple.yml
  playbooks/scenarios/test_cases/send_receive.yml
  playbooks/tofino/templates/node_setup_test_inventory.yml.j2
  trans_sec/device_software/receive_packets.py
Labels: enhancement

#356 Changed and added validation to drop report hash value
  bin/start_ae.py
  playbooks/general/templates/ae_service.sh.j2
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
  playbooks/scenarios/lab_trial/drop_report_simple.yml
  trans_sec/analytics/oinc.py
  trans_sec/bfruntime_lib/aggregate_switch.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/device_software/send_packets.py
  trans_sec/utils/tps_utils.py
Labels: enhancement

#362 Expanding data-drop tests to validate multiple reports
  playbooks/scenarios/general/drop_report_simple.yml
  playbooks/scenarios/general/drop_report_validation.yml
  playbooks/scenarios/general/drop_rpt_pkt_tasks.yml
  playbooks/scenarios/lab_trial/drop-rpt.yml
  playbooks/tofino/setup_nodes-single_switch.yml
  trans_sec/device_software/receive_packets.py
Labels: automation, enhancement

#364 TPS setup in CL lab
  automation/p4/tofino/scenarios.tf
  conf/cl_hw_lab_trial/tofino-sim-topology.yaml
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
  playbooks/scenarios/lab_trial/restart_services.yml
  playbooks/tofino/setup_tofino_switch.yml
Labels: hardware, lab trial

#367 Simple ae listen and act on drop reports
  bin/start_ae.py
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
  playbooks/scenarios/lab_trial/data_inspection_basic.yml
  playbooks/scenarios/lab_trial/pkt-flood.yml
  playbooks/scenarios/lab_trial/restart_services.yml
  tests/trans_sec/analytics/oinc_tests.py
  trans_sec/analytics/oinc.py
  trans_sec/utils/http_session.py
Labels: enhancement, lab trial

#372 Update drop count for HCP
  bin/sdn_controller.py
  playbooks/general/templates/sdn_controller.sh.j2
  trans_sec/controller/ddos_sdn_controller.py
Labels: enhancement, lab trial
