Repository cablelabs/transparent-security, pull requests merged in 2021-01, with the labels that each got.

#381 Added new web services for port management
  trans_sec/bfruntime_lib/bfrt_switch.py
  trans_sec/controller/ddos_sdn_controller.py
  trans_sec/controller/http_server_flask.py
Labels: enhancement, lab trial

#383 UDPv6 Pipeline data truncation fix ( Issue #378 )
  p4/core/core_tna.p4
Labels: bug

#384 reactivated UDP IPv6 pkt-flood tests
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
Labels: bug

#386 Bug fix when TRPT not configured and added bridge_md for all packets
  p4/aggregate/aggregate_tna.p4
  p4/core/core_tna.p4
  p4/include/tna_mirror.p4
  p4/include/tps_consts.p4
  p4/include/tps_headers.p4
  playbooks/scenarios/core/data-inspection.yml
  playbooks/scenarios/lab_trial/configure_switches-lab_trial.yml
  trans_sec/bfruntime_lib/core_switch.py
  trans_sec/controller/core_controller.py
  trans_sec/controller/http_server_flask.py
Labels: bug

#395 Added packet bytes as an attack trigger
  bin/start_ae.py
  playbooks/general/templates/ae_service.sh.j2
  playbooks/scenarios/lab_trial/all-pkt-flood.yml
  playbooks/scenarios/lab_trial/pkt-flood-simple-ae.yml
  playbooks/tofino/setup_nodes-lab_trial.yml
  trans_sec/analytics/oinc.py
Labels: enhancement
